In [1]:
import pandas as pd
import numpy as np

#### Series

In [10]:
data = [6, 89, 23, 45, 10, "python"]
s1 = pd.Series(data)
print(type(s1))
s1

<class 'pandas.core.series.Series'>

0         6
1        89
2        23
3        45
4        10
5    python
dtype: object

In [6]:
data = [6, 89, 23, 45, 10]
index_ = ["a", "b", "c", "d", "e"]
s1 = pd.Series(data, index=index_)
s1["a"]

6

In [7]:
s2 = pd.Series({"x": 20, "y": 30})
s2

x    20
y    30
dtype: int64

In [8]:
s1 = pd.Series([4, 6, 8], index=["a", "b", "c"])
s2 = pd.Series([8, 45, 23, 78], index=["a", "f", "c", "b"])
s3 = s1 + s2 
s3

a    12.0
b    84.0
c    31.0
f     NaN
dtype: float64

#### DataFrame

In [12]:
data = {
    'Patient': ['Ali', 'Sara', 'Diana', 'Reza', 'Neda', 'Omid'],
    'Age': [19, 29, 27, 45, 33, 50],
    'Diagnosis': ['Healthy', 'Hypertension', 'Diabetes', 'Flu', 'Asthma', 'Hypertension'],
    'BloodPressure': [120, 150, 130, 110, 125, 160],
    'HeartRate': [72, 88, 80, 76, 70, 90]
}
df = pd.DataFrame(data, index=["a", "b", "c", "d", "e", "f"])
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [13]:
type(df)

pandas.core.frame.DataFrame

#### Access Data

In [14]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [16]:
type(df["Age"])

pandas.core.series.Series

In [17]:
df[["Age", "BloodPressure"]]

   Age  BloodPressure
a   19            120
b   29            150
c   27            130
d   45            110
e   33            125
f   50            160

In [18]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [19]:
df["Age"] > 20

a    False
b     True
c     True
d     True
e     True
f     True
Name: Age, dtype: bool

In [21]:
df[df["Age"] > 20]["HeartRate"]

b    88
c    80
d    76
e    70
f    90
Name: HeartRate, dtype: int64

#### loc, iloc

In [22]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [23]:
# row ------> 1:4
# column ------> 1-4 
df.iloc[1:4, 1:4]

   Age     Diagnosis  BloodPressure
b   29  Hypertension            150
c   27      Diabetes            130
d   45           Flu            110

In [24]:
df.loc["b":"d", "Age":"BloodPressure"]

   Age     Diagnosis  BloodPressure
b   29  Hypertension            150
c   27      Diabetes            130
d   45           Flu            110

In [25]:
df.loc["b", "Age":"BloodPressure"]

Age                        29
Diagnosis        Hypertension
BloodPressure             150
Name: b, dtype: object

In [26]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [27]:
df.loc[::2, ["Patient", "Age", "BloodPressure"]]

  Patient  Age  BloodPressure
a     Ali   19            120
c   Diana   27            130
e    Neda   33            125

### Remove

In [28]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
a     Ali   19       Healthy            120         72
b    Sara   29  Hypertension            150         88
c   Diana   27      Diabetes            130         80
d    Reza   45           Flu            110         76
e    Neda   33        Asthma            125         70
f    Omid   50  Hypertension            160         90

In [ ]:
df.drop(columns=["Age"], inplace=True)

In [32]:
df

  Patient     Diagnosis  BloodPressure  HeartRate
a     Ali       Healthy            120         72
b    Sara  Hypertension            150         88
c   Diana      Diabetes            130         80
d    Reza           Flu            110         76
e    Neda        Asthma            125         70
f    Omid  Hypertension            160         90

In [34]:
df.drop(index="a", inplace=True)

In [35]:
df

  Patient     Diagnosis  BloodPressure  HeartRate
b    Sara  Hypertension            150         88
c   Diana      Diabetes            130         80
d    Reza           Flu            110         76
e    Neda        Asthma            125         70
f    Omid  Hypertension            160         90

### CSV

In [36]:
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

In [37]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [38]:
type(df)

pandas.core.frame.DataFrame

In [39]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [42]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [44]:
df.tail(2)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [46]:
rows, columns = df.shape
print(rows, columns)

5110 12

In [47]:
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [50]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [51]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [53]:
df["work_type"].nunique()

5

In [54]:
df["work_type"].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'],
      dtype=object)

In [55]:
df["work_type"].value_counts()

work_type
Private          2925
Self-employed     819
children          687
Govt_job          657
Never_worked       22
Name: count, dtype: int64

In [56]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [57]:
df["Residence_type"].value_counts()

Residence_type
Urban    2596
Rural    2514
Name: count, dtype: int64

In [58]:
df["smoking_status"].value_counts()

smoking_status
never smoked       1892
Unknown            1544
formerly smoked     885
smokes              789
Name: count, dtype: int64

In [59]:
df.nunique()

id                   5110
gender                  3
age                   104
hypertension            2
heart_disease           2
ever_married            2
work_type               5
Residence_type          2
avg_glucose_level    3979
bmi                   418
smoking_status          4
stroke                  2
dtype: int64

### Mapping

In [66]:
data = {
    "City": ["New York", "London", "Chicago", "Manchester"],
    "Country": ["USA", "UK", "USA", "UK"]
}
df = pd.DataFrame(data)
mapping_data = {
    "USA": "United States",
    "UK": "Englan"
}
df["Country"] = df["Country"].map(mapping_data)
city_mapping = {
    "New York" : "NYC"
}
df["City"] = df["City"].replace(city_mapping)
df

         City        Country
0         NYC  United States
1      London         Englan
2     Chicago  United States
3  Manchester         Englan

In [74]:
data = {
    'Patient': ['Ali', 'Sara', 'Diana', 'Reza', 'Neda', 'Omid'],
    'Age': [19, 29, 27, 45, 33, 50],
    'Diagnosis': [np.nan, 'Hypertension', 'Diabetes', 'Flu', 'Asthma', 'Hypertension'],
    'BloodPressure': [120, 150, np.nan, 110, np.nan, 160],
    'HeartRate': [72, np.nan, 80, 76, 70, np.nan]
}
df = pd.DataFrame(data)
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0        NaN
2   Diana   27      Diabetes            NaN       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma            NaN       70.0
5    Omid   50  Hypertension          160.0        NaN

In [ ]:
#df.fillna({"Diagnosis":"Unknown", "BloodPressure": 120.0}, inplace=True)

In [75]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0        NaN
2   Diana   27      Diabetes            NaN       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma            NaN       70.0
5    Omid   50  Hypertension          160.0        NaN

In [76]:
df.fillna(method="bfill")

/tmp/ipykernel_7140/3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19  Hypertension          120.0       72.0
1    Sara   29  Hypertension          150.0       80.0
2   Diana   27      Diabetes          110.0       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma          160.0       70.0
5    Omid   50  Hypertension          160.0        NaN

In [77]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0        NaN
2   Diana   27      Diabetes            NaN       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma            NaN       70.0
5    Omid   50  Hypertension          160.0        NaN

In [78]:
df.fillna(method="ffill")

/tmp/ipykernel_7140/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0       72.0
2   Diana   27      Diabetes          150.0       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma          110.0       70.0
5    Omid   50  Hypertension          160.0       70.0

In [79]:
df

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0        NaN
2   Diana   27      Diabetes            NaN       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma            NaN       70.0
5    Omid   50  Hypertension          160.0        NaN

In [81]:
df['BloodPressure'].fillna(df["BloodPressure"].mean(), inplace=True)
df

/tmp/ipykernel_7140/1138865605.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BloodPressure'].fillna(df["BloodPressure"].mean(), inplace=True)

  Patient  Age     Diagnosis  BloodPressure  HeartRate
0     Ali   19           NaN          120.0       72.0
1    Sara   29  Hypertension          150.0        NaN
2   Diana   27      Diabetes          135.0       80.0
3    Reza   45           Flu          110.0       76.0
4    Neda   33        Asthma          135.0       70.0
5    Omid   50  Hypertension          160.0        NaN